old_sound_rabbit_mq:
    connections:
        default:
            host:     '%env(RABBIT_MQ_HOST)%'
            port:     '%env(RABBIT_MQ_PORT)%'
            user:     '%env(RABBIT_MQ_USER)%'
            password: '%env(RABBIT_MQ_PASSWORD)%'
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        generate_sitemap:
            connection:       default
            exchange_options: { name: 'sitemap_task', type: direct }
            service_alias: generate_sitemap_producer
    consumers:
        generate_sitemap:
            connection:       default
            exchange_options: { name: 'sitemap_task', type: direct }
            queue_options:    { name: 'sitemap_task'}
            callback:         app.consumer.generate_sitemap